name: wxPython windows build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    env:
      python: "3.11"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON }}
      - name: Cache venv
        uses: actions/cache@v4
        id: cache
        with:
          path: .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel setuptools wxpython cx-freeze
      - name: cxFreeze build
        run: python setup.py build
      - name: Prepare artifact
        run: |
          mv build/exe.win-amd64-3.11/ wxtest/
          cp -r imgs wxtest/
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: wxtest
